import type { Locale } from './i18n'

const labels: Record<string, readonly [english: string, portuguese: string]> = {
  printing: ['Printing', 'Imprimindo'],
  auto_bed_leveling: ['Auto bed leveling', 'Nivelamento automático da mesa'],
  heatbed_preheating: ['Heatbed preheating', 'Pré-aquecendo a mesa'],
  vibration_compensation: ['Vibration compensation', 'Compensando vibrações'],
  changing_filament: ['Changing filament', 'Trocando o filamento'],
  m400_pause: ['M400 pause', 'Pausa M400'],
  paused_filament_runout: ['Paused: filament ran out', 'Pausada: filamento acabou'],
  heating_nozzle: ['Heating nozzle', 'Aquecendo o bico'],
  calibrating_dynamic_flow: ['Calibrating dynamic flow', 'Calibrando o fluxo dinâmico'],
  scanning_bed_surface: ['Scanning bed surface', 'Escaneando a superfície da mesa'],
  inspecting_first_layer: ['Inspecting first layer', 'Inspecionando a primeira camada'],
  identifying_build_plate_type: ['Identifying build plate', 'Identificando o tipo de mesa'],
  calibrating_micro_lidar: ['Calibrating Micro LiDAR', 'Calibrando o Micro LiDAR'],
  homing_toolhead: ['Homing toolhead', 'Referenciando o cabeçote'],
  cleaning_nozzle_tip: ['Cleaning nozzle tip', 'Limpando a ponta do bico'],
  checking_extruder_temperature: ['Checking extruder temperature', 'Verificando a temperatura da extrusora'],
  paused_by_user: ['Paused by user', 'Pausada pelo usuário'],
  paused_front_cover_fell_off: ['Paused: front cover fell off', 'Pausada: tampa frontal solta'],
  calibrating_flow_ratio: ['Calibrating flow ratio', 'Calibrando a proporção de fluxo'],
  paused_nozzle_temperature_malfunction: ['Paused: nozzle temperature fault', 'Pausada: falha na temperatura do bico'],
  paused_heatbed_temperature_malfunction: ['Paused: heatbed temperature fault', 'Pausada: falha na temperatura da mesa'],
  unloading_filament: ['Unloading filament', 'Descarregando o filamento'],
  paused_step_loss: ['Paused: step loss detected', 'Pausada: perda de passos detectada'],
  loading_filament: ['Loading filament', 'Carregando o filamento'],
  motor_noise_cancellation: ['Motor noise cancellation', 'Cancelamento de ruído dos motores'],
  paused_ams_offline: ['Paused: AMS offline', 'Pausada: AMS offline'],
  paused_low_heatbreak_fan: ['Paused: low heatbreak fan speed', 'Pausada: ventoinha do dissipador lenta'],
  paused_chamber_temperature_control: ['Paused: chamber temperature control', 'Pausada: controle de temperatura da câmara'],
  cooling_chamber: ['Cooling chamber', 'Resfriando a câmara'],
  paused_by_gcode: ['Paused by G-code', 'Pausada pelo G-code'],
  motor_noise_showcase: ['Motor noise test', 'Teste de ruído dos motores'],
  paused_nozzle_clumping: ['Paused: nozzle clumping detected', 'Pausada: acúmulo no bico detectado'],
  paused_cutter_error: ['Paused: filament cutter fault', 'Pausada: falha no cortador de filamento'],
  paused_first_layer_error: ['Paused: first layer fault', 'Pausada: falha na primeira camada'],
  paused_nozzle_clog: ['Paused: nozzle clog detected', 'Pausada: entupimento do bico detectado'],
  measuring_motion_precision: ['Measuring motion precision', 'Medindo a precisão de movimento'],
  enhancing_motion_precision: ['Enhancing motion precision', 'Aprimorando a precisão de movimento'],
  measuring_motion_accuracy: ['Measuring motion accuracy', 'Medindo a exatidão de movimento'],
  calibrating_nozzle_offset: ['Calibrating nozzle offset', 'Calibrando o deslocamento do bico'],
  high_temperature_bed_leveling: ['High-temperature bed leveling', 'Nivelamento da mesa em alta temperatura'],
  checking_quick_release_lever: ['Checking quick-release lever', 'Verificando a alavanca de liberação rápida'],
  checking_door_and_top_cover: ['Checking door and top cover', 'Verificando a porta e a tampa superior'],
  laser_calibration: ['Laser calibration', 'Calibrando o laser'],
  checking_build_platform: ['Checking build platform', 'Verificando a plataforma de impressão'],
  confirming_birdseye_camera_location: ['Confirming BirdsEye camera location', 'Confirmando a posição da câmera BirdsEye'],
  calibrating_birdseye_camera: ['Calibrating BirdsEye camera', 'Calibrando a câmera BirdsEye'],
  bed_leveling_phase_1: ['Bed leveling: phase 1', 'Nivelamento da mesa: fase 1'],
  bed_leveling_phase_2: ['Bed leveling: phase 2', 'Nivelamento da mesa: fase 2'],
  heating_chamber: ['Heating chamber', 'Aquecendo a câmara'],
  cooling_heatbed: ['Cooling heatbed', 'Resfriando a mesa'],
  printing_calibration_lines: ['Printing calibration lines', 'Imprimindo linhas de calibração'],
  checking_material: ['Checking material', 'Verificando o material'],
  calibrating_live_view_camera: ['Calibrating live-view camera', 'Calibrando a câmera de visualização'],
  waiting_for_heatbed_temperature: ['Waiting for heatbed temperature', 'Aguardando a temperatura da mesa'],
  checking_material_position: ['Checking material position', 'Verificando a posição do material'],
  calibrating_cutting_module_offset: ['Calibrating cutting-module offset', 'Calibrando o deslocamento do módulo de corte'],
  measuring_surface: ['Measuring surface', 'Medindo a superfície'],
  thermal_preconditioning: ['Thermal preconditioning', 'Pré-condicionamento térmico'],
  homing_blade_holder: ['Homing blade holder', 'Referenciando o suporte da lâmina'],
  calibrating_camera_offset: ['Calibrating camera offset', 'Calibrando o deslocamento da câmera'],
  calibrating_blade_holder_position: ['Calibrating blade-holder position', 'Calibrando a posição do suporte da lâmina'],
  hotend_pick_and_place_test: ['Hotend pick-and-place test', 'Teste de troca do hotend'],
  waiting_for_chamber_temperature: ['Waiting for chamber temperature', 'Aguardando a temperatura da câmara'],
  preparing_hotend: ['Preparing hotend', 'Preparando o hotend'],
  calibrating_nozzle_clumping_detection: ['Calibrating nozzle-clumping detection', 'Calibrando a detecção de acúmulo no bico'],
  purifying_chamber_air: ['Purifying chamber air', 'Purificando o ar da câmara'],
  preparing: ['Preparing', 'Preparando'],
  preparing_ams: ['Preparing AMS', 'Preparando o AMS'],
}

export function printStageLabel(locale: Locale, stage?: string, stageCode?: number): string | undefined {
  if (stage === undefined && stageCode === undefined) return undefined
  const label = labels[stage ?? 'preparing'] ?? labels.preparing
  return label[locale === 'pt-BR' ? 1 : 0]
}
